---
title: "AD Code"
Author: "Muhammad Elsadany"
---


```{r}
# load libraries
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(DESeq2)
library(pheatmap)
library(boxplotdbl)
library(gplots)
```



#Data retrieval part
```{r}
ADData <- read.csv("data/AD_Counts_2.csv", header=T, check.names=FALSE, row.names=1)
ADmeta <- read.csv("data/AD_Meta_2.csv", header=T, check.names = FALSE,  row.names=1)
```


#Check step
```{r}

### Check that sample names match in both files
all(colnames(ADData) %in% rownames(ADmeta))
all(colnames(ADData) == rownames(ADmeta))

```



#DESeq Object for comparing AD VS. Old
```{r}
## Create DESeq2Dataset object
ADdds <- DESeqDataSetFromMatrix(countData = ADData, colData = ADmeta, design = ~ SampleType2)
#View(counts(ADdds))
## Run analysis
ADdds <- DESeq(ADdds)
```



```{r}
print(ADdds)

```



#generating normalized counts
```{r}
ADdds2 <- estimateSizeFactors(ADdds)
ADnormalized_counts <- counts(ADdds2, normalized=TRUE)
#write.csv(ADnormalized_counts, file="data/ADnormalized_counts.csv")

```


#contrast
```{r}
## Define contrasts, extract results table, and shrink the log2 fold changes

#Define your disease group first, then your control 

contrast_ <- c("SampleType2", "AD", "Old")
resultsNames(ADdds)


res_table_unshrunken <- results(ADdds, contrast=contrast_, alpha = 0.05, lfcThreshold = 1.0)

res_table_shrunken <- lfcShrink(ADdds, contrast=contrast_, res=res_table_unshrunken, type="ashr")

```


# summary function

```{r}
## Summarize results
summary(res_table_unshrunken)

```

#saving results table
```{r}
res_table_unshrunken <- res_table_unshrunken %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
write.csv(res_table_unshrunken, file="results/AD_VS._Old_res_table_unshrunken.csv")



res_table_shrunken <- res_table_shrunken %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()
#write.csv(res_table_shrunken, file="results/AD_VS._Old_res_table_shrunken.csv")

```





#setting thresholds for DEGs
```{r}
### Set thresholds
padj.cutoff <- 0.05
lfc.cutoff <- 1.0

```


#subsetting table for DEGs values only
```{r}
sigOE <- res_table_unshrunken %>%
        filter(padj < padj.cutoff & abs(log2FoldChange) > lfc.cutoff)

write.csv(sigOE, file="results/AD_VS._Old_DEGslfc1.0.csv")
```






